openapi: 3.0.0
info:
  title: CBDC數位貨幣測試API系統
  description: 資訊安全實驗室銀行端API
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8081
    description: 銀行伺服器
tags:
  - name: "銀行API"
    description: "從銀行領錢與存款的API。"

paths:
  /api/login:
    get:
      tags:
      - "銀行API"
      summary: 登入使用者取得token。
      description: ""
      # 請求參數
      parameters:
        - name: account
          in: query
          description: 帳號
          required: true
          schema:
            type: string
            default: user
        - name: password
          in: query
          description: 密碼
          required: true
          schema:
            type: string
            default: user
      # 回應參數
      responses:
        '200':    # status code
          description: 由回應的不同表現帳號密碼是否錯誤
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: int
                    example: 1
                  message:
                    type: string
                    example: Login success.
                  token:
                    type: string
                    example: 95f585c748524b1ba154c13a37f973f4

  # /get-currency:
  #   post:
  #     tags:
  #     - "銀行API"
  #     summary: 將帳號密碼加密後，存成密文，認證成功後以提取貨幣。

  #     requestBody:
  #       description: 將帳號密碼加密後，存成密文，認證成功後以提取貨幣。
  #       required: true
  #       content:
  #         application/x-www-form-urlencoded:
  #           schema:
  #             type: object
  #             properties:
  #               cipher_user_input:
  #                 type: string      
  #     responses:
  #       200:
  #         description: 收到回傳訊息。
  #         content:
  #           application/json:
  #             schema: 
  #               type: object
  #               properties:
  #                 Status:
  #                   type: string
  #                   description: 領取成功失敗的狀態
  #                   example: Success/Fail/Decrypt fail
  #                 cipher_currency:
  #                   type: string
  #                   description: 加密後的貨幣
  #                   example: ASDASEW445323SCCFFD3232==