name: Docker Image CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Build containers
      run: docker-compose up -d

    - name: Sleep for 20 seconds
      run: sleep 20s
      shell: bash

    - name: Test Methods
      run: docker compose exec bank-django-service bash ./Test
